<?php

use Detain\MyAdminOpenSRS\OpenSRS;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 08:05:42.
 */
class OpenSRSTest extends TestCase
{
    /**
     * @var OpenSRS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OpenSRS();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::loadDomainInfo
     * @todo   Implement testLoadDomainInfo().
     */
    public function testLoadDomainInfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::getCookieRaw
     * @todo   Implement testGetCookieRaw().
     */
    public function testGetCookieRaw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::getNameserversRaw
     * @todo   Implement testGetNameserversRaw().
     */
    public function testGetNameserversRaw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::createNameserverRaw
     * @todo   Implement testCreateNameserverRaw().
     */
    public function testCreateNameserverRaw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::deleteNameserverRaw
     * @todo   Implement testDeleteNameserverRaw().
     */
    public function testDeleteNameserverRaw()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::transferCheck
     * @todo   Implement testTransferCheck().
     */
    public function testTransferCheck()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::lookupGetDomain
     * @todo   Implement testLookupGetDomain().
     */
    public function testLookupGetDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::lookupDomain
     * @todo   Implement testLookupDomain().
     */
    public function testLookupDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::checkDomainAvailable
     * @todo   Implement testCheckDomainAvailable().
     */
    public function testCheckDomainAvailable()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::lookupDomainPrice
     * @todo   Implement testLookupDomainPrice().
     */
    public function testLookupDomainPrice()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::searchDomain
     * @todo   Implement testSearchDomain().
     */
    public function testSearchDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::lock
     * @todo   Implement testLock().
     */
    public function testLock()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::whoisPrivacy
     * @todo   Implement testWhoisPrivacy().
     */
    public function testWhoisPrivacy()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::listDomainsByExpireyDate
     * @todo   Implement testListDomainsByExpireyDate().
     */
    public function testListDomainsByExpireyDate()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\MyAdminOpenSRS\OpenSRS::redeemDomain
     * @todo   Implement testRedeemDomain().
     */
    public function testRedeemDomain()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
