<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-26 at 07:10:37.
 */
class OpenSRSTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var OpenSRS
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new OpenSRS;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
